### ISSUE TITLE
[help] Create a script service for debugging scripts

### ISSUE THREAD

**Issue by zerox1212** [dreamfactorysoftware/example-scripts#4]
I'm looking for insights to make debugging DF scripts easier and avoiding putting DF into debug mode. I also don't want to SSH into the server to see what shows up in dreamfactory.log.

I have two ideas:
1. Make a script service which simply attempts to output any data passed to it. That way any script being worked on could call platform.api.post('debug', object) and the data would show up in a file _in the local file storage_.
2. Write script output to a log file which is hosted on local file service, thus avoiding SSH to the server.

I would really like to try idea 1.

Any ideas if this is possible?

**Comment by gnieark** [comment]
I have written a service script that send an email with what you want inside to debug. 

Finnaly to debug, I use error_log($varIWantToGet); php function inside DF's scripts. Logs are written in the apache log file. You can pimp it (logs files can be on a shared file) by configuring your php.ini or the vhost file.
